version: '3.3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data_new:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
  backend:
    image: gelyamolodets/foodgram:latest
    restart: always
#    build:
#      context: ../backend
#      dockerfile: Dockerfile
    ports:
        - 8000:8000
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - .env
  frontend:
    image: gelyamolodets/foodgram_frontend
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - static_value:/static/
      - media_value:/media/
      - ./nginx:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml

volumes:
  result_build:
  postgres_data_new:
  static_value:
  media_value:
