# Generated by Django 3.0.5 on 2021-07-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.CreateModel(
            name='TagsInRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='api_v1.Recipe', verbose_name='Рецепт')),
                ('tag', models.ForeignKey(blank=True, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='api_v1.Tag', verbose_name='Название тега')),
            ],
        ),
    ]
