# Generated by Django 3.0.5 on 2021-07-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20210719_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_timetime',
            new_name='cooking_time',
        ),
        migrations.AlterField(
            model_name='tagsinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api_v1.Recipe', verbose_name='Рецепт'),
        ),
    ]
