# Generated by Django 3.0.5 on 2021-07-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20210719_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsFavorited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Избранное')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_favorited', to='api_v1.Recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
