# Generated by Django 3.0.5 on 2021-07-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_auto_20210726_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
