# Generated by Django 3.0.5 on 2021-07-31 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0014_auto_20210730_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsinrecipe',
            name='tag',
            field=models.ForeignKey(blank=True, max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='tags_in_recipe', to='api_v1.Tag', verbose_name='Название тега'),
        ),
    ]
