# Generated by Django 3.0.5 on 2021-07-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0015_auto_20210731_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(blank=True, max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='api_v1.Ingredient', verbose_name='Название продукта'),
        ),
    ]
